{
 "about": {
  "channels": [
   "conda-forge",
   "defaults"
  ],
  "conda_build_version": "3.17.6",
  "conda_private": false,
  "conda_version": "4.5.12",
  "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
  "doc_url": "http://ftfy.readthedocs.io/",
  "env_vars": {
   "CIO_TEST": "<not set>"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "rmax"
   ]
  },
  "home": "https://github.com/LuminosoInsight/python-ftfy/",
  "identifiers": [],
  "keywords": [],
  "license": "MIT",
  "license_file": "LICENSE.txt",
  "root_pkgs": [
   "anaconda-client 1.7.2 py37_0",
   "asn1crypto 0.24.0 py37_0",
   "beautifulsoup4 4.6.3 py37_0",
   "bzip2 1.0.6 h1de35cc_5",
   "ca-certificates 2018.03.07 0",
   "certifi 2018.11.29 py37_0",
   "cffi 1.11.5 py37h6174b99_1",
   "chardet 3.0.4 py37_1",
   "click 7.0 py37_0",
   "clyent 1.2.2 py37_1",
   "conda 4.5.12 py37_0",
   "conda-build 3.17.6 py37_0",
   "conda-env 2.6.0 1",
   "conda-forge-ci-setup 2.1.1 py37_0",
   "cryptography 2.4.2 py37ha12b0ac_0",
   "decorator 4.3.0 py37_0",
   "filelock 3.0.10 py37_0",
   "glob2 0.6 py37_1",
   "icu 58.2 h4b95b61_1",
   "idna 2.8 py37_0",
   "ipython_genutils 0.2.0 py37_0",
   "jinja2 2.10 py37_0",
   "jsonschema 2.6.0 py37_0",
   "jupyter_core 4.4.0 py37_0",
   "libarchive 3.3.3 h786848e_5",
   "libcxx 4.0.1 hcfea43d_1",
   "libcxxabi 4.0.1 hcfea43d_1",
   "libedit 3.1.20170329 hb402a30_2",
   "libffi 3.2.1 h475c297_4",
   "libiconv 1.15 hdd342a3_7",
   "liblief 0.9.0 h2a1bed3_0",
   "libxml2 2.9.8 hab757c2_1",
   "lz4-c 1.8.1.2 h1de35cc_0",
   "lzo 2.10 h362108e_2",
   "markupsafe 1.1.0 py37h1de35cc_0",
   "nbformat 4.4.0 py37_0",
   "ncurses 6.1 h0a44026_1",
   "openssl 1.1.1a h1de35cc_0",
   "pip 18.1 py37_0",
   "pkginfo 1.4.2 py37_1",
   "psutil 5.4.8 py37h1de35cc_0",
   "py-lief 0.9.0 py37hd4eaf27_0",
   "pycosat 0.6.3 py37h1de35cc_0",
   "pycparser 2.19 py37_0",
   "pyopenssl 18.0.0 py37_0",
   "pysocks 1.6.8 py37_0",
   "python 3.7.1 haf84260_7",
   "python-dateutil 2.7.5 py37_0",
   "python-libarchive-c 2.8 py37_6",
   "python.app 2 py37_9",
   "pytz 2018.7 py37_0",
   "pyyaml 3.13 py37h1de35cc_0",
   "readline 7.0 h1de35cc_5",
   "requests 2.21.0 py37_0",
   "ruamel_yaml 0.15.46 py37h1de35cc_0",
   "setuptools 40.6.3 py37_0",
   "six 1.12.0 py37_0",
   "sqlite 3.26.0 ha441bb4_0",
   "tk 8.6.8 ha441bb4_0",
   "tqdm 4.28.1 py37h28b3542_0",
   "traitlets 4.3.2 py37_0",
   "urllib3 1.24.1 py37_0",
   "wheel 0.32.3 py37_0",
   "xz 5.2.4 h1de35cc_4",
   "yaml 0.1.7 hc338f04_2",
   "zlib 1.2.11 h1de35cc_3",
   "zstd 1.3.7 h5bba6e5_0"
  ],
  "summary": "Fixes some problems with Unicode text after the fact",
  "tags": []
 },
 "conda_build_config": {
  "CONDA_BUILD_SYSROOT": "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk",
  "MACOSX_DEPLOYMENT_TARGET": "10.9",
  "build_number_decrement": "0",
  "c_compiler": "clang",
  "channel_sources": "conda-forge,defaults",
  "channel_targets": "conda-forge main",
  "cpu_optimization_target": "nocona",
  "cran_mirror": "https://cran.r-project.org",
  "cxx_compiler": "clangxx",
  "docker_image": "condaforge/linux-anvil",
  "extend_keys": [
   "ignore_version",
   "extend_keys",
   "ignore_build_only_deps",
   "pin_run_as_build"
  ],
  "fortran_compiler": "gfortran",
  "ignore_build_only_deps": [
   "numpy",
   "python"
  ],
  "lua": "5",
  "macos_machine": "x86_64-apple-darwin13.4.0",
  "macos_min_version": "10.9",
  "numpy": "1.11",
  "perl": "5.26.0",
  "pin_run_as_build": {
   "python": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   },
   "r-base": {
    "max_pin": "x.x.x",
    "min_pin": "x.x.x"
   }
  },
  "python": "3.6",
  "r_base": "3.5",
  "target_platform": "osx-64",
  "zip_keys": [
   [
    "channel_sources",
    "channel_targets",
    "build_number_decrement"
   ]
  ]
 },
 "files": [
  "bin/ftfy",
  "lib/python3.6/site-packages/ftfy-5.5.0-py3.6.egg-info/PKG-INFO",
  "lib/python3.6/site-packages/ftfy/__init__.py",
  "lib/python3.6/site-packages/ftfy/bad_codecs/__init__.py",
  "lib/python3.6/site-packages/ftfy/bad_codecs/sloppy.py",
  "lib/python3.6/site-packages/ftfy/bad_codecs/utf8_variants.py",
  "lib/python3.6/site-packages/ftfy/badness.py",
  "lib/python3.6/site-packages/ftfy/build_data.py",
  "lib/python3.6/site-packages/ftfy/char_classes.dat",
  "lib/python3.6/site-packages/ftfy/chardata.py",
  "lib/python3.6/site-packages/ftfy/cli.py",
  "lib/python3.6/site-packages/ftfy/fixes.py",
  "lib/python3.6/site-packages/ftfy/formatting.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py36_1000",
  "build_number": 1000,
  "depends": [
   "python >=3.6,<3.7.0a0",
   "setuptools",
   "wcwidth"
  ],
  "license": "MIT",
  "name": "ftfy",
  "platform": "osx",
  "subdir": "osx-64",
  "timestamp": 1547134928319,
  "version": "5.5.0"
 },
 "metadata_version": 1,
 "name": "ftfy",
 "raw_recipe": "{% set name = \"ftfy\" %}\n{% set version = \"5.5.0\" %}\n\npackage:\n  name: {{ name }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.tar.gz\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: 525ea45a871f52ddb170e66b01f35f1b3022995016c81efa305e628937b85443\n\nbuild:\n  number: 1000\n  script: \"{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv\"\n  skip: True  # [py2k or py>36]\n  entry_points:\n    - ftfy = ftfy.cli:main\n\nrequirements:\n  host:\n    - python\n    - pip\n  run:\n    - python\n    # Required for loading package data via `pkg_resources` module.\n    - setuptools\n    - wcwidth\n\ntest:\n  requires:\n    - pytest\n  source_files:\n    - tests\n  commands:\n    - py.test --deselect tests/test_cli.py  # [win]\n    # CLI tests fail on windows.\n    - py.test  # [not win]\n\nabout:\n  home: https://github.com/LuminosoInsight/python-ftfy/\n  license: MIT\n  license_file: LICENSE.txt\n  summary: Fixes some problems with Unicode text after the fact\n  dev_url: https://github.com/LuminosoInsight/python-ftfy\n  doc_url: http://ftfy.readthedocs.io/\n\nextra:\n  recipe-maintainers:\n    - rmax\n",
 "rendered_recipe": {
  "about": {
   "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
   "doc_url": "http://ftfy.readthedocs.io/",
   "home": "https://github.com/LuminosoInsight/python-ftfy/",
   "license": "MIT",
   "license_file": "LICENSE.txt",
   "summary": "Fixes some problems with Unicode text after the fact"
  },
  "build": {
   "entry_points": [
    "ftfy = ftfy.cli:main"
   ],
   "number": "1000",
   "script": "/Users/travis/miniconda3/conda-bld/ftfy_1547134855461/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv",
   "string": "py36_1000"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "rmax"
   ]
  },
  "package": {
   "name": "ftfy",
   "version": "5.5.0"
  },
  "requirements": {
   "host": [
    "ca-certificates 2018.11.29 ha4d7672_0",
    "certifi 2018.11.29 py36_1000",
    "libffi 3.2.1 hfc679d8_5",
    "ncurses 6.1 hfc679d8_2",
    "openssl 1.0.2p h470a237_2",
    "pip 18.1 py36_1000",
    "python 3.6.7 h5001a0f_1",
    "readline 7.0 haf1bffa_1",
    "setuptools 40.6.3 py36_0",
    "sqlite 3.26.0 hb1c47c0_0",
    "tk 8.6.9 ha92aebf_0",
    "wheel 0.32.3 py36_0",
    "xz 5.2.4 h470a237_1",
    "zlib 1.2.11 h470a237_4"
   ],
   "run": [
    "python >=3.6,<3.7.0a0",
    "setuptools",
    "wcwidth"
   ]
  },
  "source": {
   "fn": "ftfy-5.5.0.tar.gz",
   "sha256": "525ea45a871f52ddb170e66b01f35f1b3022995016c81efa305e628937b85443",
   "url": "https://pypi.io/packages/source/f/ftfy/ftfy-5.5.0.tar.gz"
  },
  "test": {
   "commands": [
    "py.test"
   ],
   "requires": [
    "pytest"
   ],
   "source_files": [
    "tests"
   ]
  }
 },
 "version": "5.5.0"
}